In [32]:
import pandas as pd
df = pd.read_csv("edu_sur.csv")
df.head()

,id,TIMESTAMP,STUDENT_NAME,SUBJECT_NAME,TOUGHNESS_LEVEL,TYPE_OF,SUBJECT_SYLLABUS,PREFERRED_READING,INTEREST_LEVEL,SUPPORTING_KNOWLEDGE,...,CURRENT_STATUS,NUMBER_OF,DUE_DATE,DESIRED_NUMBER,CHECKING_LEVEL,MARKS_IN,EDUCATION_TYPE,SEMESTER,AS_PER,PRED_HOUR
0,234,12/20/2018 6:38,Prateek modi,cg,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Intermediate,...,10,0,12/20/2018 6:38,50,Lenient,45.0,Graduation,1,1.0,1.0
1,233,12/20/2018 6:38,Prateek modi,cg,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,...,9,0,12/20/2018 6:38,50,Lenient,45.0,Graduation,1,6.0,6.0
2,232,12/20/2018 6:38,Prateek modi,cg,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,...,10,0,12/20/2018 6:38,50,Lenient,30.0,Graduation,1,1.0,1.0
3,231,12/20/2018 6:37,Prateek modi,cg,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,...,7,0,12/20/2018 6:37,50,Lenient,30.0,Graduation,1,6.0,6.0
4,230,12/20/2018 5:37,Pratik,NP,Easy,Theoritical,Short,Notes,Very Interesting,Intermediate,...,10,0,12/20/2018 5:37,40,Lenient,50.0,Graduation,1,2.0,2.0

In [33]:
df.drop(["id","SUBJECT_NAME","TIMESTAMP","STUDENT_NAME","EDUCATION_TYPE","PRED_HOUR","DUE_DATE"],axis = 1, inplace=True)

In [34]:
df.head()

,TOUGHNESS_LEVEL,TYPE_OF,SUBJECT_SYLLABUS,PREFERRED_READING,INTEREST_LEVEL,SUPPORTING_KNOWLEDGE,AVERAGE_READING,CURRENT_STATUS,NUMBER_OF,DESIRED_NUMBER,CHECKING_LEVEL,MARKS_IN,SEMESTER,AS_PER
0,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Intermediate,4,10,0,50,Lenient,45.0,1,1.0
1,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,5,9,0,50,Lenient,45.0,1,6.0
2,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,5,10,0,50,Lenient,30.0,1,1.0
3,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,5,7,0,50,Lenient,30.0,1,6.0
4,Easy,Theoritical,Short,Notes,Very Interesting,Intermediate,2,10,0,40,Lenient,50.0,1,2.0

In [35]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 14 columns):
TOUGHNESS_LEVEL         242 non-null object
TYPE_OF                 242 non-null object
SUBJECT_SYLLABUS        242 non-null object
PREFERRED_READING       242 non-null object
INTEREST_LEVEL          242 non-null object
SUPPORTING_KNOWLEDGE    242 non-null object
AVERAGE_READING         242 non-null int64
CURRENT_STATUS          242 non-null int64
NUMBER_OF               242 non-null int64
DESIRED_NUMBER          242 non-null int64
CHECKING_LEVEL          242 non-null object
MARKS_IN                242 non-null float64
SEMESTER                242 non-null int64
AS_PER                  242 non-null float64
dtypes: float64(2), int64(5), object(7)
memory usage: 26.5+ KB

,TOUGHNESS_LEVEL,TYPE_OF,SUBJECT_SYLLABUS,PREFERRED_READING,INTEREST_LEVEL,SUPPORTING_KNOWLEDGE,AVERAGE_READING,CURRENT_STATUS,NUMBER_OF,DESIRED_NUMBER,CHECKING_LEVEL,MARKS_IN,SEMESTER,AS_PER
0,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Intermediate,4,10,0,50,Lenient,45.0,1,1.0
1,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,5,9,0,50,Lenient,45.0,1,6.0
2,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,5,10,0,50,Lenient,30.0,1,1.0
3,Easy,Theoritical,Lengthy (600+ pages),Notes,Interesting,Beginner,5,7,0,50,Lenient,30.0,1,6.0
4,Easy,Theoritical,Short,Notes,Very Interesting,Intermediate,2,10,0,40,Lenient,50.0,1,2.0

In [36]:
df.describe(include= object)

,TOUGHNESS_LEVEL,TYPE_OF,SUBJECT_SYLLABUS,PREFERRED_READING,INTEREST_LEVEL,SUPPORTING_KNOWLEDGE,CHECKING_LEVEL
count,242,242,242,242,242,242,242
unique,3,4,4,4,4,4,3
top,Easy,Theoritical,Very Lengthy (800+ pages),Notes,Very Interesting,None,Strict
freq,124,145,109,152,115,111,119

In [37]:
df = pd.get_dummies(df)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 33 columns):
AVERAGE_READING                               242 non-null int64
CURRENT_STATUS                                242 non-null int64
NUMBER_OF                                     242 non-null int64
DESIRED_NUMBER                                242 non-null int64
MARKS_IN                                      242 non-null float64
SEMESTER                                      242 non-null int64
AS_PER                                        242 non-null float64
TOUGHNESS_LEVEL_Easy                          242 non-null uint8
TOUGHNESS_LEVEL_Hard                          242 non-null uint8
TOUGHNESS_LEVEL_Medium                        242 non-null uint8
TYPE_OF_Numerical                             242 non-null uint8
TYPE_OF_Other                                 242 non-null uint8
TYPE_OF_Practical                             242 non-null uint8
TYPE_OF_Theoritical                           242 non-null uint8
SUBJECT_SYLLABUS_Lengthy (600+ pages)         242 non-null uint8
SUBJECT_SYLLABUS_Medium (400+ pages)          242 non-null uint8
SUBJECT_SYLLABUS_Short                        242 non-null uint8
SUBJECT_SYLLABUS_Very Lengthy (800+ pages)    242 non-null uint8
PREFERRED_READING_Book                        242 non-null uint8
PREFERRED_READING_Multiple                    242 non-null uint8
PREFERRED_READING_Notes                       242 non-null uint8
PREFERRED_READING_Video                       242 non-null uint8
INTEREST_LEVEL_Boring                         242 non-null uint8
INTEREST_LEVEL_Interesting                    242 non-null uint8
INTEREST_LEVEL_Normal                         242 non-null uint8
INTEREST_LEVEL_Very Interesting               242 non-null uint8
SUPPORTING_KNOWLEDGE_Beginner                 242 non-null uint8
SUPPORTING_KNOWLEDGE_Expert                   242 non-null uint8
SUPPORTING_KNOWLEDGE_Intermediate             242 non-null uint8
SUPPORTING_KNOWLEDGE_None                     242 non-null uint8
CHECKING_LEVEL_Lenient                        242 non-null uint8
CHECKING_LEVEL_Normal                         242 non-null uint8
CHECKING_LEVEL_Strict                         242 non-null uint8
dtypes: float64(2), int64(5), uint8(26)
memory usage: 19.5 KB

In [39]:
y = df["AS_PER"]
x = df.drop("AS_PER", axis = 1)

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x, y, test_size = 0.1, random_state = 7)

In [96]:
# from xgboost import XGBRegressor
# model = XGBRegressor(random_state = 6)
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state = 6,n_estimators=10)

In [97]:
model.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=6, verbose=0, warm_start=False)

In [98]:
model.predict(x_test)

array([184.6       ,   2.4       ,   8.78      ,   5.2       ,
        17.66166667, 171.8       ,   6.        ,   6.        ,
        51.7       ,  47.46666667,  18.9       , 163.        ,
        17.9       ,  34.3       , 185.9       ,   0.        ,
         9.5       ,   0.42174603,  36.76666667,  72.        ,
         4.2       ,   1.36174603,  16.92      ,  15.        ,
        19.07      ])

In [99]:
y_test

80     200.0
129      2.0
3        6.0
184     10.5
177     27.0
145    115.0
94       6.0
88       7.0
120     42.0
50      18.0
95      12.0
82     200.0
24      50.0
180     22.0
81     200.0
22       0.0
164      6.0
240      0.0
11      16.0
121     60.0
2        1.0
126      1.0
161      9.0
224     15.0
160     12.0
Name: AS_PER, dtype: float64

In [100]:
model.score(x_test, y_test)

0.919976147416006

In [101]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,model.predict(x_test))

322.31367152960445

In [16]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
import numpy as np
model = XGBClassifier(eta=0.0)
random_grid = {'n_estimators': [int(x) for x in np.linspace(start=180, stop=196, num = 16)]}
# random_grid = {'eta': [x for x in np.linspace(start=0, stop=0.4, num = 10)]}
# rf_random = RandomizedSearchCV(estimator = model, param_distributions = random_grid, cv = 4)
rf_random = GridSearchCV(model, random_grid, cv=5)
rf_random.fit(X_train, y_train)
print(rf_random.best_score_)
rf_random.best_params_

NameError: name 'XGBClassifier' is not defined